SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[cars]'
GO
ALTER TABLE [dbo].[cars] ADD
[color] [varchar] (25) NULL
GO

-- test comment
